### ISSUE TITLE
Internal error during ABAP Code Search Query

### ISSUE THREAD

**Issue by Jules1337dev** [DevEpos/abap-code-search-tools#8]
Hi Ludwig,

it´s me again. Since i updated the Backend for the Code Search Plugin yesterday, the Code Search do not work anymore. The popup appears as usual but, when searching anything this error occurs.

![image](https://github.com/DevEpos/abap-code-search-tools/assets/84089388/69fb5400-d4d7-4f27-89db-f1b6cf9ef234)

May you help here?

Best regards
Julian

**Comment by stockbal** [comment]
Hi Julian,

easy enough 😊. You just have to update the ADT Plug-in in Eclipse.
This is kind of message is always an indicator that the plug-in and ABAP backend are out of sync. So one or the other needs to be updated.

Regards,
Ludwig

**Comment by Jules1337dev** [comment]
Unfortunately my eclipse says "there are no updates :/"

**Comment by stockbal** [comment]
Hm,

so, the newest Eclipse version should be 1.8.0.202305271941. I tested this version with the current branches nw-7.40 and main, so there should be no issue. 

I can think of only 2 solutions:
1. Restart Eclipse and test if issue still persists
2. Clean out old plug-in sources from eclipse installation
   a) Close Eclipse 
   b) Run the following command in the eclipse installation folder (location of eclipse.exe):  
       `eclipse -application org.eclipse.equinox.p2.garbagecollector.application`
   c) Restart Eclipse
   
Regards,
Ludwig

**Comment by stockbal** [comment]
`org.eclipse.zest.core` has nothing to do with my plug-ins:
You get the installed version via "Help -> About Eclipse IDE"
![image](https://github.com/DevEpos/abap-code-search-tools/assets/35834861/3613c0f1-84cc-4851-af85-a534678e190e)

Did you also check that all XSLTs after the last pull were activated?

**Comment by Jules1337dev** [comment]
I do not see the DevEpos Features there. Is there any other way to see them?

![image](https://github.com/DevEpos/abap-code-search-tools/assets/84089388/7cba6833-9262-43c7-ac71-bd0c3b5156bc)

**Comment by stockbal** [comment]
Yes, via "Installation Details"
![image](https://github.com/DevEpos/abap-code-search-tools/assets/35834861/14d36b8d-d100-4801-ae0d-b4d3fa85c88a)

**Comment by Jules1337dev** [comment]
Seems like the Version is too old?
![image](https://github.com/DevEpos/abap-code-search-tools/assets/84089388/5cb412b3-6099-4b95-9140-b1421cbd590c)

**Comment by stockbal** [comment]
Correct.
I am not sure why you do not get the the new version. 

If you restart your eclipse and go to "Help -> Install New Software..." and then enter my Update Site (via dropdown or manually <https://eclipse.devepos.com/latest>) Eclipse should fetch the newest versions

**Comment by Jules1337dev** [comment]
It works! 
i am also confused why the marketplace does not show me an update
